{
 "title": "c advisor docker",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_period{job=\"integrations/cadvisor\"}"
    },
    { "expr": "container_spec_cpu_shares" }
   ]
  },
  {
   "title": "container last seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    { "expr": "time() - container_last_seen{}" }
   ]
  },
  {
   "title": "cpu_usage_seconds_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{job=\"integrations/cadvisor\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "network receive/sent bytes total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{job=\"integrations/cadvisor\"}",
     "legendFormat": "{{interface}}.receive"
    },
    {
     "expr": "container_network_transmit_bytes_total{job=\"integrations/cadvisor\"}",
     "legendFormat": "{{interface}}.transmit"
    }
   ]
  },
  {
   "title": "Machine CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{job=\"integrations/cadvisor\"}"
    },
    {
     "expr": "machine_cpu_physical_cores{job=\"integrations/cadvisor\"}"
    },
    {
     "expr": "machine_cpu_sockets{job=\"integrations/cadvisor\"}"
    },
    {}
   ]
  },
  {
   "title": "container_cpu_load_average_10s",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{job=\"integrations/cadvisor\"}"
    },
    {
     "expr": "container_cpu_system_seconds_total{job=\"integrations/cadvisor\"}"
    },
    {
     "expr": "container_cpu_user_seconds_total{job=\"integrations/cadvisor\"}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "container_memory_rss{job=\"integrations/cadvisor\"}"
    }
   ]
  },
  {
   "title": "Memory swap",
   "type": "timeseries",
   "description": "Memory swap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "container_memory_swap{job=\"integrations/cadvisor\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{}",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}